Update install script for better prerequisites installation.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -5,7 +5,23 @@ set -e
 ################## Variables ###################################################
 
 # Packages required for script to run.
-which git 2>/dev/null || { sudo apt-get install -y -q git >/dev/null; }
-which ansible 2>/dev/null || { sudo apt-get install -y -q ansible >/dev/null ; }
+MISSING_PREREQUISITES=()
+
+if ! [ -x "$(command -v git)" ]; then
+  MISSING_PREREQUISITES+=("git")
+fi
+
+if ! [ -x "$(command -v ansible)" ]; then
+  MISSING_PREREQUISITES+=("ansible")
+fi
+
+# If missing prerequisites is not empty.
+if (( ${#MISSING_PREREQUISITES[@]} )); then
+  green=`tput setaf 2`
+  yellow=`tput setaf 3`
+  reset=`tput sgr0`
+  echo "${green}Installing prerequisite apt packages: ${yellow}${MISSING_PREREQUISITES[*]}${reset}"
+  sudo apt-get install -y -q ${MISSING_PREREQUISITES[*]} >/dev/null
+fi
 
 ansible-playbook playbook.yml --ask-become-pass "$@"
